// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrtterltzjdmrxdmnclr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFydHRlcmx0empkbXJ4ZG1uY2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTU3NjIsImV4cCI6MjA2MTE3MTc2Mn0.Mh0tGyY67ZA_SPtI7FtISsDdi3Lv_mc0b0qI4lNNlFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);